version: "3.9"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "P@ss@0rd!!!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - "sql-vol:/var/opt/mssql"
volumes:
  sql-vol:
    external: true
